services:
  mock-payment-provider:
    build:
      context: .
    image: mock-payment-provider:local
    ports:
      - "9081:9081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/providerdb
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      PAYMENT_SERVICE_WEBHOOK_URL: http://payment-service:8082/api/payments/webhook
    networks:
      - bridge-network
    restart: unless-stopped
    labels:
      - "dozzle.group=app"

networks:
  bridge-network:
    external: true
