spring.application.name=payment-provider
server.port=9081
spring.datasource.url=jdbc:postgresql://localhost:5432/providerdb
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:payment}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

payment-service.webhook-url=${PAYMENT_SERVICE_WEBHOOK_URL:http://payment-service:8082/api/payments/webhook}

springdoc.swagger-ui.path=/swagger-ui.html
